/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import { _b } from '@ctx-core/object'
import type { svg_Ctx } from './svg_Ctx'
import type { set_svg_matrix2d_T } from './set_svg_matrix2d_b'
import { set_svg_matrix2d_b } from './set_svg_matrix2d_b'
import type { svg_content_height$_T } from './svg_content_height$_b'
import { svg_content_height$_b } from './svg_content_height$_b'
import type { svg_content_width$_T } from './svg_content_width$_b'
import { svg_content_width$_b } from './svg_content_width$_b'
import type { svg_height$_T } from './svg_height$_b'
import { svg_height$_b } from './svg_height$_b'
import type { svg_margin$_T } from './svg_margin$_b'
import { svg_margin$_b } from './svg_margin$_b'
import type { svg_matrix2d_ctx$_T } from './svg_matrix2d_ctx$_b'
import { svg_matrix2d_ctx$_b } from './svg_matrix2d_ctx$_b'
import type { svg_width$_T } from './svg_width$_b'
import { svg_width$_b } from './svg_width$_b'
export interface svg_ctx_I {
	set_svg_matrix2d?:set_svg_matrix2d_T
	svg_content_height$?:svg_content_height$_T
	svg_content_width$?:svg_content_width$_T
	svg_height$?:svg_height$_T
	svg_margin$?:svg_margin$_T
	svg_matrix2d_ctx$?:svg_matrix2d_ctx$_T
	svg_width$?:svg_width$_T
	svg_b_h?:svg_b_h_T
}
export interface svg_b_h_T {
	get set_svg_matrix2d():set_svg_matrix2d_T
	get svg_content_height$():svg_content_height$_T
	get svg_content_width$():svg_content_width$_T
	get svg_height$():svg_height$_T
	get svg_margin$():svg_margin$_T
	get svg_matrix2d_ctx$():svg_matrix2d_ctx$_T
	get svg_width$():svg_width$_T
}
export function svg_b_h_b(ctx:svg_Ctx):svg_b_h_T {
	return _b<svg_Ctx, 'svg_b_h'>('svg_b_h', ()=>{
		return {
			get set_svg_matrix2d() { return set_svg_matrix2d_b(ctx) },
			get svg_content_height$() { return svg_content_height$_b(ctx) },
			get svg_content_width$() { return svg_content_width$_b(ctx) },
			get svg_height$() { return svg_height$_b(ctx) },
			get svg_margin$() { return svg_margin$_b(ctx) },
			get svg_matrix2d_ctx$() { return svg_matrix2d_ctx$_b(ctx) },
			get svg_width$() { return svg_width$_b(ctx) }
		}
	})(ctx)
}