/*
 * This file was generated by `npm run generate_ctx_I_file` in @ctx-core/dev-tools
*/
import type { set_svg_matrix2d_T } from './set_svg_matrix2d_b.js'
import type { svg_content_height$_T } from './svg_content_height$_b.js'
import type { svg_content_width$_T } from './svg_content_width$_b.js'
import type { svg_height$_T } from './svg_height$_b.js'
import type { svg_margin$_T } from './svg_margin$_b.js'
import type { svg_matrix2d_ctx$_T } from './svg_matrix2d_ctx$_b.js'
import type { svg_width$_T } from './svg_width$_b.js'
export interface svg_ctx_I {
	set_svg_matrix2d?:set_svg_matrix2d_T
	svg_content_height$?:svg_content_height$_T
	svg_content_width$?:svg_content_width$_T
	svg_height$?:svg_height$_T
	svg_margin$?:svg_margin$_T
	svg_matrix2d_ctx$?:svg_matrix2d_ctx$_T
	svg_width$?:svg_width$_T
}